apiVersion: v1
kind: Namespace
metadata:
  name: application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-app
  namespace: application
spec:
  replicas: 10  # Установите общее количество реплик, которое будет распределено по воркерам
  selector:
    matchLabels:
      app: my-nginx-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
      - name: my-nginx-app
        image: wineperm/my-nginx-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      topologySpreadConstraints:
      - maxSkew: 5  # Увеличиваем maxSkew для более гибкого распределения
        topologyKey: "kubernetes.io/hostname"
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: my-nginx-app
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx-app-service
  namespace: application
spec:
  selector:
    app: my-nginx-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      nodePort: 32000
  type: NodePort
