name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@latest

    - name: Log in to Yandex Container Registry
      uses: docker/login-action@latest
      with:
        registry: cr.yandex
        username: oauth
        password: ${{ secrets.YANDEX_IAM_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@latest
      with:
        context: .
        push: true
        tags: cr.yandex/crp8qogn8i9j95t88e78/my-nginx-app:latest
        no-cache: true
